import { Columns } from "./components/attendees/attendance-table";

export const dummyEvents = [
    {
        title: "Tech Innovators Meetup",
        description:
            "A gathering of students and professionals to share ideas on emerging technologies and AI applications.",
        status: "Upcoming",
        attendees: 120,
        date: "2025-10-15",
        location: "NU Laguna Auditorium",
        time: "2:00 PM - 5:00 PM",
    },
    {
        title: "Frontend Design Workshop",
        description:
            "An interactive session focusing on modern UI/UX trends and responsive web design using Tailwind CSS.",
        status: "Ongoing",
        attendees: 75,
        date: "2025-10-11",
        location: "Innovation Hub, Room 204",
        time: "9:00 AM - 12:00 PM",
    },
    {
        title: "AI Hackathon 2025",
        description:
            "A 24-hour coding challenge where teams develop AI-powered solutions to real-world problems.",
        status: "Upcoming",
        attendees: 200,
        date: "2025-11-05",
        location: "TechPark Convention Center",
        time: "8:00 AM - 8:00 AM (next day)",
    },
    {
        title: "Community Cleanup Drive",
        description:
            "Join fellow students in cleaning and revitalizing nearby parks and waterways for a greener community.",
        status: "Completed",
        attendees: 58,
        date: "2025-09-20",
        location: "Calamba Eco Park",
        time: "7:00 AM - 11:00 AM",
    },
    {
        title: "Project QOL Demo Day",
        description:
            "A showcase of the Project QOL prototype with live demos and developer insights.",
        status: "Upcoming",
        attendees: 95,
        date: "2025-10-25",
        location: "NU Laguna Tech Hall",
        time: "1:00 PM - 4:00 PM",
    },
    {
        title: "Cybersecurity Awareness Seminar",
        description:
            "Learn best practices for online safety, data privacy, and protection against cyber threats.",
        status: "Upcoming",
        attendees: 60,
        date: "2025-10-18",
        location: "NU Laguna Lecture Hall 3",
        time: "10:00 AM - 1:00 PM",
    },
    {
        title: "Mobile App Development Bootcamp",
        description:
            "Hands-on session on building mobile apps using Flutter and React Native, from design to deployment.",
        status: "Ongoing",
        attendees: 40,
        date: "2025-10-12",
        location: "Innovation Lab, Room 101",
        time: "9:00 AM - 5:00 PM",
    },
    {
        title: "Environmental Awareness Talk",
        description:
            "Guest speakers discuss climate change, sustainable practices, and how students can make an impact.",
        status: "Upcoming",
        attendees: 80,
        date: "2025-10-22",
        location: "NU Laguna Auditorium",
        time: "3:00 PM - 5:00 PM",
    },
    {
        title: "Student Leadership Workshop",
        description:
            "Develop leadership skills, teamwork, and project management techniques through interactive exercises.",
        status: "Completed",
        attendees: 50,
        date: "2025-09-28",
        location: "Innovation Hub, Room 205",
        time: "1:00 PM - 4:00 PM",
    },
    {
        title: "Game Development Hackathon",
        description:
            "A competitive 48-hour event where teams create fun and innovative games using Unity and Unreal Engine.",
        status: "Upcoming",
        attendees: 150,
        date: "2025-11-12",
        location: "NU Laguna Tech Hall",
        time: "8:00 AM - 8:00 PM (next day)",
    },
];

export const dummyClubs = [
  {
    logo: "https://via.placeholder.com/80?text=Org1",
    name: "Tech Innovators Club",
    description: "A group of students passionate about emerging technologies and AI.",
    pastEvents: 12,
    upcomingEvents: 3,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org2",
    name: "Creative Coders",
    description: "Focusing on innovative coding projects and hackathons.",
    pastEvents: 8,
    upcomingEvents: 2,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org3",
    name: "Design Hub",
    description: "Exploring modern UI/UX trends and design thinking.",
    pastEvents: 15,
    upcomingEvents: 4,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org4",
    name: "AI & Robotics Society",
    description: "Bringing together enthusiasts of AI, robotics, and automation.",
    pastEvents: 20,
    upcomingEvents: 5,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org5",
    name: "Community Volunteers",
    description: "Organizing social and environmental projects for the community.",
    pastEvents: 10,
    upcomingEvents: 1,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org6",
    name: "Music Makers",
    description: "For students passionate about composing, producing, and performing music.",
    pastEvents: 7,
    upcomingEvents: 3,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org7",
    name: "Sports Alliance",
    description: "Promoting teamwork and wellness through sports activities.",
    pastEvents: 18,
    upcomingEvents: 6,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org8",
    name: "Entrepreneurship Club",
    description: "Helping students build business ideas and startup ventures.",
    pastEvents: 9,
    upcomingEvents: 2,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org9",
    name: "Environmental Advocates",
    description: "Raising awareness on climate change and sustainability projects.",
    pastEvents: 14,
    upcomingEvents: 3,
  },
  {
    logo: "https://via.placeholder.com/80?text=Org10",
    name: "Gaming Community",
    description: "Connecting gamers for tournaments, events, and streaming content.",
    pastEvents: 5,
    upcomingEvents: 1,
  },
];


export const dummyTableData: Columns[] = [
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
    {
        id: "1",
        time_in: "2023-06-10T09:00:00",
        name: "John Doe",
        email: "john.doe@example.com",
        time_out: "2023-06-10T17:00:00",
        isMember: true,
    },
    {
        id: "2",
        time_in: "2023-06-10T09:15:00",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        time_out: "2023-06-10T17:30:00",
        isMember: false,
    },
    {
        id: "3",
        time_in: "2023-06-10T08:45:00",
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        time_out: "2023-06-10T16:45:00",
        isMember: true,
    },
];
