name: Lint

on:
  # Run this workflow when commits are pushed to `main` and on pull requests targeting `main`.
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering from the Actions tab

concurrency:
  # Ensure only one run per branch/workflow group is active at a time.
  # If a new push arrives while the previous run is still running, the previous
  # run will be cancelled. The group name uses the workflow and ref so that
  # concurrency is scoped per-branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache npm and node_modules
        # Cache node modules and the npm cache to speed up repeated runs. The
        # cache key includes hashes of `package-lock.json` and `package.json` so
        # the cache is invalidated automatically when dependencies change.
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          # Key includes both lockfile and package.json so cache updates when deps change
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run ESLint
        run: npm run lint
          if [ -f package-lock.json ]; then
          npm ci --silent
          fi
          npm run lint
